[package]
name = "mtext"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4.27"
regex = "1.11.1"
sensible-env-logger = "0.3"
tera = "1.20.0"
walkdir = "2"
